@publicPath = http://localhost:3030

GET {{publicPath}}/questions

###

POST {{publicPath}}/questions
Content-Type: application/json

{
  "title": "this is fuck, this is",
  "content": "this is fuck you, this",
  "tags": ["1", "2"]
}

###
DELETE {{publicPath}}/questions/6
